on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - dev
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep (SAST)
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: semgrep ci
